//
// Created by sid on 29/11/23.
//
#pragma once
// NOLINTBEGIN
#ifndef MANIFOLD_MAX_EXP_REF_INPUT
#define MANIFOLD_MAX_EXP_REF_INPUT 5
#endif

#ifndef MANIFOLD_MAX_EXP_REF_OUTPUT
#define MANIFOLD_MAX_EXP_REF_OUTPUT 5
#endif


#ifndef MANIFOLD_MAX_EXP_INPUT
#define MANIFOLD_MAX_EXP_INPUT 10
#endif


#ifndef MANIFOLD_MAX_EXP_OUTPUT
#define MANIFOLD_MAX_EXP_OUTPUT 2
#endif


#ifndef MANIFOLD_MAX_RANK
#define MANIFOLD_MAX_RANK 5
#endif


#ifndef MANIFOLD_TENSORNODE_MAX_OUT
#define MANIFOLD_TENSORNODE_MAX_OUT 20
#endif

#ifndef MANIFOLD_STATIC_GRAPH_MAX_OP
#define MANIFOLD_STATIC_GRAPH_MAX_OP 10
#endif

 #ifndef MANIFOLD_PARAM_BYTES_MAX
 #define MANIFOLD_PARAM_BYTES_MAX 256
 #endif
// NOLINTEND
