macro(Scions_enable_ipo)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT result OUTPUT output LANGUAGES CXX)
    if (result)
        if (CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -flto=thin")
        elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -flto=10")
        elseif (CMAKE_CXX_COMPILER_ID MATCHES "IntelLLVM")
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -flto=thin")
        endif ()
    else ()
        message(SEND_ERROR "IPO is not supported: ${output} ${CMAKE_CXX_COMPILER_ID}")
    endif ()
endmacro()
